### ISSUE TITLE
LDAP测试提示invalid filter

### ISSUE THREAD

**Issue by gaoyuke** [getway/diting#3]
![image](https://user-images.githubusercontent.com/31268133/55534751-bffd6680-56e7-11e9-85c5-8d8b2708541e.png)

**Comment by getway** [comment]
@gaoyuke (uid=%(user)s) 这个试一下哈

**Comment by gaoyuke** [comment]
> @gaoyuke (uid=%(user)s) 这个试一下哈

那天我直接把他默认的sAMAccountName改成这个就可以了 忘记关闭这个issue了 谢谢你
